### ISSUE TITLE
Feature suggestion: automatic mode switching based on time

### ISSUE THREAD

**Issue by macgyver** [Exelord/dark-mode#2]
Many people use something to cover their laptop cameras when not in use, e.g. https://supporters.eff.org/shop/laptop-camera-cover-set

For such people, checking the ambient light is not possible because the camera is covered up most of the time. It would be nice to have a second mechanism to trigger automatic changes based on system time and sunset information.

What do you think?

**Comment by Exelord** [comment]
Implemented :)
