### ISSUE TITLE
Auto change doesn't works in my configuration 

### ISSUE THREAD

**Issue by idoo** [Exelord/dark-mode#3]
@Exelord thank you for implementing this, I've looked to way how I can get access from light sensor in js :)

Does it work in current Mac OS? looks like we don't have access to sensor now, is it right?

I have macbook pro 2016:
Atom: 1.23.3 x64
mac os 10.13.3

**Comment by Exelord** [comment]
:) 
I'm using dark-mode all the time and on the latest osx and atom, it works perfectly :)

Take a look to package.json There is a package responsible for ambient light sensor. Anyway. It's also implemented already in Chrome, but not activated by default

**Comment by idoo** [comment]
yep, I looked on this, and even tried to compile it

maybe something wrong with my settings — are you using default values?

**Comment by Exelord** [comment]
On more thing. Where are u using it? I mean in what environment. Atom
package, node server, browser?

**Comment by idoo** [comment]
now I'm trying your package in atom, is it possible to get some data from atom console? when I'm using 
`new AmbientLightSensorReading(null)`
it returns 
`AmbientLightSensorReading {illuminance: 0, timeStamp: 325720.09}` for me
so, I guess there are no data from a sensor, isn't it?

**Comment by Exelord** [comment]
I see, but is the package working correctly for you or it is just the problem with accessing the sensor package?

**Comment by idoo** [comment]
I install it, set parameters like here
http://take.ms/wqZgy
and put some light on my sensor, and nothing was changed :(
then I tried to debug it from atom console, and don't know how to get access to sensor :(

**Comment by Exelord** [comment]
<img width="597" alt="screen shot 2018-02-01 at 09 54 09" src="https://user-images.githubusercontent.com/1469375/35669583-de27d1a2-0735-11e8-8215-07e14b2a8d19.png">
Please ensure to turn auto mode to on

**Comment by idoo** [comment]
yep, I switched it on as well

**Comment by Exelord** [comment]
Did you restart the atom? What kind of mac you have?

**Comment by idoo** [comment]
yep, I did, macbook pro 2016

**Comment by Exelord** [comment]
Hmm, same. Is the switcher working correctly?

**Comment by idoo** [comment]
yep, I can switch manually, but can't automatically

I did debug here — lib/ambient-light.js:41

and looks value is always `0` even my screen is changing the brightness level

I have:
Atom: 1.23.3 x64
mac os 10.13.3

**Comment by Exelord** [comment]
```js
darkMode = atom.packages.getAvailablePackages().find((p) => {return p.name == 'dark-mode'})
Ambient = require(`${darkMode.path}/lib/ambient-light`);
sensor = new Ambient();
sensor._lux();
```

Try it out in developer console and check what is the result of `sensor._lux()`

**Comment by idoo** [comment]
I did almost same when I put debugger in `lib/ambient-light.js:41` — value is 0
maybe I have add/update some library?

**Comment by Exelord** [comment]
:/ looks bad... and weird. Try to execute this file: https://github.com/jamo/ambientlight/blob/master/ambientlight.mm

**Comment by Exelord** [comment]
Its definitely not a problem of the package, rather the system configuration.

**Comment by idoo** [comment]
yep, I think so
```
./ambientlight                                                                                                                                                                                               
failed to find ambient light sensors
```

**Comment by idoo** [comment]
@Exelord last question, do you have touchbar?
looks like here is same issue with macbook with touchbar
https://github.com/Dunedan/mbp-2016-linux/issues/16

**Comment by Exelord** [comment]
No. :/

**Comment by QuentinRoy** [comment]
Same issue here. I tried your snippet above in Atom's console. Value is 0 as well. I believe I have the exact same issue as @idoo. I also have a MacBook equipped with their new (useless) touchbar. So it might be a good lead.

**Comment by Exelord** [comment]
Im going to switch to native api https://developer.mozilla.org/en-US/docs/Web/API/Ambient_Light_Events

**Comment by idoo** [comment]
@Exelord sadly, it's doesn't work as well, coz as I got it's using same `AppleLMUController` :(
and ask I can see it works only in FF now

**Comment by Exelord** [comment]
checkout this example:
```js
window.addEventListener('devicelight', function(event) { console.log('Light: ', event.value) })
```

It works, I have it already implemented. Just testing now for a few days to setup correct threshold

**Comment by QuentinRoy** [comment]
It is (partially) supported on chrome since quite some time so it should be supported by nodejs as well. However it does not work on my laptop (I just tried both your snippet and [this website](https://whatwebcando.today/ambient-light.html)).

**Comment by Exelord** [comment]
Hmm, in the latest atom it works perfectly fine

**Comment by QuentinRoy** [comment]
It does look like a good idea to rely on a standard (though unfinished). In that case you might choose to wait for Chromium to fix it (not sure when that will happen), meaning that you have nothing to do. An other option would be to wait for an update from  [ambientlight](https://github.com/jamo/ambientlight). Its maintainer mentioned that he was willing to have a look at it (c.f. https://github.com/jamo/ambientlight/issues/1).

**Comment by idoo** [comment]
I did 
```
window.addEventListener('devicelight', function(event) {
  console.log(event.value);
});
```

and there is no result in latest FF, Chrome, Safari

**Comment by Exelord** [comment]
Could you try that one in the atom?

**Comment by Exelord** [comment]
@QuentinRoy sure... For now, I will migrate to browser api, but depending what will came faster we will react with a proper fix.

**Comment by idoo** [comment]
looks like atom returns `Infinity` if there are no sensor data
![bridge 2018-02-22 20-29-03](https://user-images.githubusercontent.com/738921/36540991-08cd4344-180f-11e8-9292-303e16fb2075.png)

**Comment by Exelord** [comment]
I will open a PR soon, so you will be able to test it

**Comment by idoo** [comment]
looks like it's doesn't work in FF
![what we can do today 2018-02-22 20-30-49](https://user-images.githubusercontent.com/738921/36541074-5636a152-180f-11e8-98fb-5f7255a5a7a0.png)

Chrome/Safari/  — both Not supported

**Comment by Exelord** [comment]
Yes, but atom is based on chromium.

**Comment by Exelord** [comment]
and we need only window.ondevicelight :)

**Comment by idoo** [comment]
Funny, in Atom it works, but with `Infinity` as constant
![bridge 2018-02-22 20-34-45](https://user-images.githubusercontent.com/738921/36541229-d497e556-180f-11e8-87a2-c485b52cb76b.png)

**Comment by idoo** [comment]
I just tested in macbook 2017 without touchbar, where data though `AppleLMUController` work well, and in Chrome `ondevicelight` and `AmbientLightSensor` is `NotSupported`

**Comment by Exelord** [comment]
yes.. in chrome `ondevicelight` is not supported yet. But chorme != chromium

**Comment by idoo** [comment]
I know, just funny :)

**Comment by Exelord** [comment]
It looks like there is no support for now mackbooks yet :/ Or the API is private

**Comment by idoo** [comment]
@Exelord btw, https://github.com/Exelord/dark-mode/issues/2 partially it can solve our pain :) I used it same configuration in emacs and it works well based on geo-coordinates and sunrise data

**Comment by Exelord** [comment]
Yes, that would be pretty cool feature :)

**Comment by idoo** [comment]
@Exelord `navigator.geolocation.getCurrentPosition(console.log)` works well :)
https://github.com/mourner/suncalc

**Comment by Exelord** [comment]
Look like getting current location is not possible in Atom. The only thing we can do is to use current timezone

**Comment by idoo** [comment]
@Exelord 
```
if (navigator.geolocation) {
  navigator.geolocation.getCurrentPosition(function(msg) {
        console.log(msg);
  }, function(err) {
        console.log(err);
  });
} else {
  error('not supported');
}
```
makes request to google, but it returns 400
`"Network location provider at 'https://www.googleapis.com/' : Returned error code 400."`

As option, it can be static longitude-latitude coordinates

Probably it require https://github.com/electron/electron/blob/master/docs/api/environment-variables.md#google_api_key

**Comment by idoo** [comment]
for history — asked for help in chromium issues tracker
https://bugs.chromium.org/p/chromium/issues/detail?id=817725&can=2&start=0&num=100&q=-component%3ABlink%3ESensor%20&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=
