### ISSUE TITLE
Info notification appear on each new window

### ISSUE THREAD

**Issue by vinkla** [Exelord/dark-mode#9]
Whenever I open a new window the `Dark Mode: Automatic mode is: ON/OFF` notification appears in the top right corner. Due to how fast the notification is closing I'm guessing this isn't the expected behaviour. 

Below is an example:

![screen recording 2018-10-23 at 13 18 18](https://user-images.githubusercontent.com/499192/47357396-de861d00-d6c6-11e8-9732-19eb71eedaa1.gif)

I'm guessing it has something todo with the following code:

https://github.com/Exelord/dark-mode/blob/872dde7db39defb877571e637a395db77f79e13e/lib/dark-mode.js#L56-L65

Let me know if there is any other information I can provide.

**Comment by Exelord** [comment]
Hmm... thats intresting. I will take a look on that :) thanks
